# -*- coding: utf-8 -*-
"""GO_STP_7724 AAMIR P.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kgeI-JRduFvdsxNKqXWPEjTdkIYMJOAh

**DAY 2: ASSIGNMENT 1 (PYTHON EXERCISES)**

**DATE: 21 MAY 2021**

**AUTHOR: AAMIR P**

**REG. ID: GO_STP_7724**

Q1. We are having 3 list like this

Colors=[“Yellow”,”Green”,”White”,”Black”]

Fruits=[“Apple”,”Papaya”,”Mango”,”Orange”]

Animals=[“Tiger”,”Lion”,”Deer”,”Zebra”]

i. Write a program that asks user to enter a Color/Fruit/Animal name and it should tell which category belongs to , like          its is a fruit or color or Animal

ii. Write a program that asks user to enter two cities and it tells you if they both are in same country or not. For               example if I enter yellow and Black, it will print "Both are colors" but if I enter yellow and Tiger it should print           "They don't belong to same category"
"""

#i)
Colors=["Yellow","Green","White","Black"]

Fruits=["Apple","Papaya","Mango","Orange"]

Animals=["Tiger","Lion","Deer","Zebra"]


a = input("Enter your data: ")
if a in Colors:
  print("It is in Colors category")
elif a in Fruits:
  print(" It is in Fruits category")
elif a in Animals:
  print("It is in Animals category")

#ii)
Cities = ["Chennai", "Bangalore", "Hyderabad"]
b = input("Enter the first city: ")
c = input("Enter the second city: ")
if b and c in Cities:
  print("They both are in same country")
else:
  print("They do not belong to same country")

"""Q2. Write a python program that can tell you if your grade score good or not . Good Score range is 40 to 60.

  i. Ask user to enter his score.

  ii. If it is below 40 to 60 range then print that score is low

  iii. If it is above 60 then print that it is good otherwise print that it is normal
"""

d =eval(input("Enter your grade: "))
if d<40:
  print("Score low")
elif 40<d<60:
  print("Score is Normal")
else:
  print("Score is Good")

"""Q3. After appearing in exam 10 times you got this result,

result = ["Pass","Fail","Fail","Pass","Fail","Pass","Pass","Fail","Fail","Fail"]

Using for loop figure out how many times you got Pass
"""

result = ["Pass","Fail","Fail","Pass","Fail","Pass","Pass","Fail","Fail","Fail"]
e=result.count("Pass")
print(e)

"""Q4. Write a program that prints following shape

"""

*
**
***
****
*****
****
***
**
*

for i in range(0,6):
  for j in range(i):
    print("*",end="")
  print()
for i in range(4,0,-1):
  for j in range(i):
    if(j<i):
      print("*",end="")
  print()

"""Q5.Lets say you are running a 50 km race. Write a program that,

Upon completing each 10 km asks you "are you tired?" If you reply "yes" then it should break and print "you didn't finish the race" If you reply "no" then it should continue and ask "are you tired" on every km If you finish all 50 km then it should print congratulations message.
"""

distance = 0
for distance in range(0,51):
  if distance<50 and distance%10==0:
    print("Are you tired?")
    racer=input()
    if racer=="yes":
      print("you didn't finish the race")
      break
    else: 
      if racer=="no":
        continue
  if distance == 50:
    print("Congratulations")

"""Q6. Write a Python program to find those numbers which are divisible by 7 and multiple of 5, between 1500 and 2700 (both included)."""

for i in range(1500,2701):
  if(i%7==0 and i%5==0):
    print(i)

"""Q7. Print square of all numbers between 10 to 20 except even numbers"""

for i in range(10, 21):
  if i%2!=0:
    print(i*i)

"""Q8. Your Marks for five Test(test1 to test5) looks like this,

marks_list = [65, 75, 2100, 95, 83]

Write a program that asks you to enter marks and program should tell you in which test that expense occurred. If expense is not found then it should print that as well.
"""

marks_list = [65, 75, 2100, 95, 83]
marks = int(input("Enter marks: "))
if marks in marks_list:
  print(f"The expense has occured in : {marks_list.index(marks)+1}")